
services:
  db:
    image: postgres:16-alpine
    container_name: tnc-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - tnc-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build: .
    # image: ghcr.io/andreufa/tnc-server:1.0
    container_name: tnc-server
    # Пробрасываем порты на хост
    ports:
      - "8080:8080"
      - "9001:9001"
    # Явно передаём переменные в контейнер.
    # Если переменной нет в .env или CI, будет использовано значение после :-
    environment:
      HTTP_ADDR: ${HTTP_ADDR:-:8080}
      CRYPTO_TCP_ADDR: ${CRYPTO_TCP_ADDR:-:9001}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-tnc}
      DB_PASSWORD: ${DB_PASSWORD:-tnc}
      DB_NAME: ${DB_NAME:-tnc}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
      SESSION_SECRET: ${SESSION_SECRET}
      BOOTSTRAP_ADMIN_USER: ${BOOTSTRAP_ADMIN_USER}
      BOOTSTRAP_ADMIN_PASSWORD: ${BOOTSTRAP_ADMIN_PASSWORD}
    # env_file оставляем только для fallback (если вдруг что-то не передали)
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  tnc-pgdata:
